---
name: WLED Proxy
version: 0.0.2
slug: wled_ingress_proxy
description: nginx reverse proxy to expose network resources through HA ingress
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
init: false
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
options:
  destination: "http://10.11.11.39"
schema:
  destination: str?
